# Generated by Django 4.1.3 on 2022-12-29 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('use', models.TextField()),
                ('number_of_units', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ghost',
            fields=[
                ('ghost_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('ghost_picture', models.ImageField(blank=True, upload_to='ghost_picture/')),
                ('height', models.PositiveIntegerField(blank=True)),
                ('weight', models.PositiveIntegerField(blank=True)),
                ('strength', models.CharField(blank=True, max_length=100)),
                ('weakness', models.CharField(blank=True, max_length=100)),
                ('special_ability', models.CharField(blank=True, max_length=100)),
                ('last_encounter_date', models.DateField(blank=True)),
                ('last_encounter_time', models.TimeField(blank=True)),
                ('last_encounter_place', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
