# Generated by Django 4.1.6 on 2023-05-04 08:05

from django.db import migrations, models
import django.db.models.deletion
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('ghosts_and_equipments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ectoplasm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255)),
                ('location', location_field.models.plain.PlainLocationField(max_length=63)),
                ('quantity', models.PositiveIntegerField()),
                ('belong_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ghosts_and_equipments.ghost')),
            ],
        ),
    ]
