# Generated by Django 4.1.6 on 2023-05-04 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ghosts_and_equipments', '0002_ectoplasm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ectoplasm',
            name='city',
        ),
    ]
