# Generated by Django 4.1.3 on 2023-02-01 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ghosts_and_equipments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission_name', models.CharField(max_length=100)),
                ('mission_date', models.DateField()),
                ('description', models.TextField()),
                ('is_complete', models.BooleanField(default=False)),
                ('encountered_ghosts', models.ManyToManyField(blank=True, related_name='encountered_ghosts', to='ghosts_and_equipments.ghost')),
                ('equipment_used', models.ManyToManyField(blank=True, related_name='equipment_used', to='ghosts_and_equipments.equipment')),
            ],
        ),
    ]
