# Generated by Django 4.1.3 on 2023-01-29 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ghosts_and_equipments', '0001_initial'),
        ('missions', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Missions',
            new_name='Mission',
        ),
    ]
